### ISSUE TITLE
Implement a UI for Test Profiles CRUD

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1306]
**Description**
We already have a PR drafted which would introduce three endpoints regarding user test profiles for Create, Read, Delete operations.
Considering the following will be merged soon, we need to take next steps on building a UI for Test Profiles.

- [ ] Create a prototype UI to Create & Show & Delete user-profiles.
- [ ] Invoke a UI to directly use the created test-profiles for a load test.
- [ ] Implementation of a grid-like CRD page for better UX.
- [ ] Segregation of Test Results which are run under a common test-profile.
- [ ] If possible, writing some unit tests using Cypress for all the new components.

**Additional Comments**
Considering this will be a completely new module in our project, we can try to use TDD for the following module & see how it goes.

**Comment by tripathyprateek** [comment]
Hi if this issue is not been worked upon, can I be assigned to do this?

**Comment by Nikhil-Ladha** [comment]
> Hi if this issue is not been worked upon, can I be assigned to do this?

Hi @tripathyprateek I am working on it, just a bit slow.

**Comment by tripathyprateek** [comment]
> > Hi if this issue is not been worked upon, can I be assigned to do this?
> 
> Hi @tripathyprateek I am working on it, just a bit slow.

okay sure. Can you recommend any other issue which I can work upon?

**Comment by Nikhil-Ladha** [comment]
Ping me on slack. Let's talk there. 🙂
