### ISSUE TITLE
M2: General Interface to Load Generators

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#211]
**Description**
See #126 for full description of Load Generator Integration Epic.

**Milestone 2: Build and Packaging**

- [ ] Create an alias type “SupportedLoadTestMethods” of type int. 
- [ ] Define constants for each of the supported load test methods.
  - [ ] HTTP
  - [ ] gRPC
  - [ ] TCP
- [ ] Create an interface with common methods for all the load generators “LoadGeneratorInterface”. Methods we need in the interface at the moment:
  - [ ] SupportedMethods() []
  - [ ] SupportedLoadTestMethods
RunLoadTest(*models.LoadTestOptions) (map[string]interface{}, *periodic.RunnerResults, error)

- [ ] Move the fortio code, which is directly accessed by meshery today, under an implementation of “LoadGeneratorInterface”, “FortioLoadGenerator”.
- [ ] Update the existing handlers to work with instances of the interface to remove the tight coupling (the instances can be created in main and propagated into the handler instance).

**Additional context**
See [Load Generator Integration design doc](https://docs.google.com/document/d/1jZMOih3Qn1ixrq1Ve6fkdZZ4TuKNoF_qfClDZTnLNcw/edit#).

**Comment by leecalcote** [comment]
@girishranganathan in consideration of the [Meshery Extension Points](https://docs.google.com/document/d/1E7NWFy5ZVEPX2W892mfVG-3yku1uci2KRDU42tNRZwA/edit) doc, do we consider this general interface complete? 

// @raghavaggarwal99

**Comment by leecalcote** [comment]
@kushthedude given PR #1180, will you update the tasks in this issue to reflect current status?

**Comment by kushthedude** [comment]
@leecalcote The last part should fix when we have gRPC test functionality also.
