### ISSUE TITLE
[mesheryctl] [epic] provide support for `platform: kubernetes`

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2307]
**Prologue**
Getting Meshery up and running locally on a Docker-enabled system is easy with Meshery’s command line interface, [mesheryctl](https://docs.meshery.io/guides/mesheryctl). The same ease by which Meshery is deployed to a Docker host should be afforded for deployments to Kubernetes clusters - different types of Kubernetes clusters.

**Current Scenario**
While the Meshery contexts contained within `config.yaml` offer configuration of the type of platform to deploy Meshery, currently only `platform: docker` is supported.

**Desired Scenario**
Also support `platform: kubernetes` across all `mesheryctl` commands.

**Epic Acceptance Tests**
1. Each `system` command considers for context platform type “kubernetes”
1. Support `platform: kubernetes` in mesheryctl context (in `config.yaml`) and across all `mesheryctl system` commands.

**_Future_**
1. Consider supporting specific Kubernetes platforms like AKS, EKS, GKE, OpenShift, Minikube, Docker Desktop and so on. Example: `platform: eks`.
1. Review `mesheryctl system config` in consideration for being implicitly executed as part of `mesheryctl system context` or `system start`.

**Child Issues**
- [x] Issue #2308 [mesheryctl] [child] platform support for Kubernetes in `system start`(`platform: kubernetes`)
- [x]  Issue #2309 [mesheryctl] [child] platform support during “bash script” installation(`platform: kubernetes`)
- [x]  Issue #2310 [mesheryctl] [child] make `system reset` platform aware(`platform: kubernetes`)
- [x]  Issue #2311 [mesheryctl] [child] make `system stop` platform aware(`platform: kubernetes`)
- [x] Issue #2312 [mesheryctl] [child] make `system logs` platform aware(`platform: kubernetes`)
- [x]  Issue #2514 [mesheryctl] [child] make `system status` platform aware(`platform: kubernetes`)
- [x] Issue #2561 [mesheryctl] [child] make `system update` platform aware(`platform: kubernetes`)

**Comment by navendu-pottekkat** [comment]
The only thing left is the platform awareness in the bash script installation. Should be fixed for v0.6

**Comment by leecalcote** [comment]
Wow. This is excellent.

**Comment by navendu-pottekkat** [comment]
All the child issues mentioned in this epic is done. Closing this issue.
