### ISSUE TITLE
[mesheryctl] (epic) `perf` commands for performance tests

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2823]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Meshery supports running performance tests using SMP. Users can also use performance profiles in the UI to save their performance tests.

#### Desired Behavior

`mesheryctl` should also have a similar user experience to the GUI.

It should also have CRUD commands to manage performance profiles and test results.

The following features need to be added-

1. `mesheryctl` only supports performance tests currently, but should support performance profiles.
2. Users should be able to run performance tests with SMP compatible files stored locally or in GitHub.
3. `perf list` and `perf view` should be added as two new subcommands to list and view both performance profiles and results within each profile. 
4. The displayed output will be in a tabular form unless specified otherwise with the `-o json` flag.
5. An `--all` flag will be supported in the `view` command to view all the results.

Please refer to "[Design Spec: `mesheryctl perf` commands](https://docs.google.com/document/d/1znOqTofsXkcPTF1AXVVSHGEZa5kue6G8vGHM4nsc2tc/edit#heading=h.blih70a9hxp)" for detailed information about this feature.

#### Child Issues

The following issues needs to be closed to mark this feature as complete-

- [ ] [[mesheryctl] Invoke test via Performance Profile](#2824)
- [ ] [[mesheryctl] List all Performance Profiles](#2825)
- [ ] [[mesheryctl] List all test results for a Performance Profile](#2826)
- [ ] [[mesheryctl] View Performance Profile’s Configuration](#2827)
- [ ] [[mesheryctl] View Details of a Test Result of Performance Profile](#2828)

Related issues can be fixed simultaneously.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by navendu-pottekkat** [comment]
@aneeshnema , A good project to take lead on.

**Comment by piyushsingariya** [comment]
let's head on with this!
